title: Corvins Paris-Austausch 2026
latest_post_is_home: true

lang: de
locale: de_DE

fallback-description: Der Blog für die Daheimgebliebenen
home_description: Wöchentliche Updates zu Corvins Erlebnissen in Paris
fallback-image: assets/share-card.jpg

url: https://corvin.sydow.ch
baseurl: /paris2026

exclude:
  - "*.sh"
  - post-template.md
  - pages/home.md

defaults:
  - scope:
      path: "_posts"
      type: "posts"
    values:
      layout: post
      permalink: /:short_month-:day:output_ext

picture_tag:
  max_dim: 1600
  quality: 85
  mobile_breakpoint: 768
  desktop_slot: 1080px
